/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { Projects } from '../Models/ProjectsModel';

export class ProjectsService {
  private static readonly dataSourceName = 'projects';

  public static async create(record: Omit<Projects, 'ID'>): Promise<IOperationResult<Projects>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<Projects, 'ID'>, Projects>(
      ProjectsService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<Projects, 'ID'>>): Promise<IOperationResult<Projects>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<Projects, 'ID'>>, Projects>(
      ProjectsService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ProjectsService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<Projects>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<Projects>(
      ProjectsService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<Projects[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<Projects>(
      ProjectsService.dataSourceName,
      options
    );
    return result;
  }
}
