/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { Users } from '../Models/UsersModel';

export class UsersService {
  private static readonly dataSourceName = 'users';

  public static async create(record: Omit<Users, 'ID'>): Promise<IOperationResult<Users>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<Users, 'ID'>, Users>(
      UsersService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<Users, 'ID'>>): Promise<IOperationResult<Users>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<Users, 'ID'>>, Users>(
      UsersService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(UsersService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<Users>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<Users>(
      UsersService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<Users[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<Users>(
      UsersService.dataSourceName,
      options
    );
    return result;
  }
}
